name: dcli_core
version: 8.4.2
homepage: https://dcli.onepub.dev
documentation: https://dcli.onepub.dev
description: A collection of functions that allow you to interact with the file system and OS environment
  from any platform that supports dart:io.  Copy, move, delete files and directory trees, search for files, create
  temp files and directories. 
repository: https://github.com/onepub-dev/dcli
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  async: ^2.5.0
  circular_buffer: ^0.12.0
  collection: ^1.15.0
  crypto: ^3.0.1
  dcli_common: ^8.4.2
  ffi: ^2.1.0
  logging: ^1.0.2
  meta: ">=1.11.0 <2.0.0"
  path: ^1.8.0
  scope: ^5.0.0
  stack_trace: ^1.10.0
  uuid: ^4.1.0
dev_dependencies:
  lint_hard: ^7.1.2
  synchronized: ^3.1.0
  test: ^1.24.7
platforms:
  android:
  ios:
  linux:
  macos:
  windows:
