name: dcli_core
version: 4.0.0
homepage: https://dcli.onepub.dev
documentation: https://dcli.onepub.dev
description: The core asyncronous functions used by dcli. DCli uses waitFor to eliminate async code in the DCli libraries which precludes DCli's usage in non-cli apps (e.g. you can't use it in flutter). The aim of dcli_core is to expose a significant set of the core dcli functions as async version so that dcli_core can be used in any project. DCli will then rely on dcli_core for core parts of its implemenation to avoid duplicating code between the two packages.
repository: https://github.com/onepub-dev/dcli
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  async: ^2.5.0
  circular_buffer: ^0.11.0
  collection: ^1.15.0
  crypto: ^3.0.1
  dcli_common: ^4.0.0
  ffi: ^2.1.0
  logging: ^1.0.2
  meta: ">=1.11.0 <2.0.0"
  path: ^1.8.0
  scope: ^4.0.0
  stack_trace: ^1.10.0
  uuid: ^4.1.0
dev_dependencies:
  lint_hard: ^4.0.0
  synchronized: ^3.1.0
  test: ^1.24.7
platforms:
  android:
  ios:
  linux:
  macos:
  windows:
