name: dcli_core
version: 0.0.4
homepage: https://dcli.noojee.dev
documentation: https://dcli.noojee.dev
description: The core asyncronous functions used by dcli. DCli uses waitFor to eliminate async code in the DCli libraries which precludes DCli's usage in non-cli apps (e.g. you can't use it in flutter). The aim of dcli_core is to expose a significant set of the core dcli functions as async version so that dcli_core can be used in any project. DCli will then rely on dcli_core for core parts of its implemenation to avoid duplicating code between the two packages.
repository: https://github.com/noojee/dcli_core
environment: 
  sdk: '>=2.14.1 <3.0.0'
dependencies: 
  async: ^2.5.0
  circular_buffer: ^0.10.0
  collection: ^1.15.0
  crypto: ^3.0.1
  meta: ^1.3.0
  path: ^1.8.0
  stacktrace_impl: ^2.0.1
  uuid: ^3.0.0
dev_dependencies: 
  lints: ^1.0.0
  test: ^1.0.0
