name: dcli_test
description: Test code used by dcli - not for general use.
version: 8.4.1
repository: https://github.com/onepub-dev/dcli/tree/master/dcli_test

environment:
  sdk: '>=3.2.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  dcli: ^8.4.1
  dcli_common: ^8.4.1
  dcli_core: ^8.4.1
  file: ^7.0.0
  meta: ">=1.11.0 <2.0.0"
  path: ^1.8.3
  scope: ^5.0.0
  stack_trace: ^1.11.1
  test: ^1.24.7
  uuid: ^4.1.0
  # path: ^1.8.0

dev_dependencies:
  lint_hard: ^7.0.1
