name: dcli_sdk
version: 4.0.1-beta.4
homepage: https://dcli.onepub.dev
documentation: https://dcli.onepub.dev
description: Dart console SDK - write console (cli) apps/scripts using dart.
repository: https://github.com/onepub-dev/dcli
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  dcli: ^4.0.1-beta.4
  dcli_common: ^4.0.1-beta.4
  dcli_core: ^4.0.1-beta.4
  dcli_terminal: ^4.0.1-beta.4
  meta: ">=1.11.0 <2.0.0"
  path: ^1.8.3
  pub_semver: ^2.1.4
  pubspec_lock: ^3.0.2
  pubspec_manager: ^1.0.0
  scope: ^4.1.0
  stack_trace: ^1.11.1
  strings: ^3.0.0
  win32: ^4.0.0
 
dev_dependencies:
  dcli_test:
  lint_hard: ^4.0.0
  test: ^1.24.7
executables:
  dcli:
  dcli_complete:
  dcli_install:
platforms:
  linux:
  macos:
  windows:
