name: dcli_unit_tester
version: 8.4.1
description: This project allows dcli to unit test functions that behave differently when installed via 'dart pub global activate'. It serves no other useful purpose so do not install!
repository: https://github.com/onepub/dcli
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  args: ^2.3.0
  dcli: ^8.4.1
  dcli_core: ^8.4.1
  dcli_terminal: ^8.4.1
  path: ^1.8.0
  strings: ^4.0.1
dev_dependencies:
  lint_hard: ^7.0.1
executables:
  dcli_unit_tester:
