name: dshell
version: 1.1.1-dev.2
homepage: https://github.com/bsutton/dshell
description: An API and dev environment for writing console apps/scripts using dart. e.g. allows you to build bash style scripts with dart.
environment: 
  sdk: '>=2.6.0 <3.0.0'
dependencies: 
  args: ^1.5.2
  collection: ^1.14.12
  file_utils: ^0.1.3
  path: ^1.6.4
  yaml: ^2.2.0
  intl: ^0.16.0
  logger: ^0.8.0
  recase: ^3.0.0
  money2: ^1.0.5
  pubspec: ^0.1.3
  pub_semver: ^1.4.2
  file: ^5.1.0
  equatable: ^1.0.1
dev_dependencies: 
  test: ^1.6.0
  mockito: ^4.1.1
  pedantic: ^1.8.0
executables: 
  dshell: dshell
  dshell_complete: dshell_complete
