name: scriptname
version: 0.0.1
description: test of command arg passing.

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter:

dependencies:
  args: ^2.0.0
  dcli: 6.0.5

dev_dependencies:
  lint_hard: ^5.0.0
