name: full
version: 0.0.1
description: A sample command-line application that installs and runs mailhog
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter:

dependencies:
  args: ^2.5.0
  dcli: 4.0.0
  dcli_core: 4.0.0
  http: ^1.2.1
  path: ^1.9.0
  settings_yaml: ^8.0.1
dev_dependencies:
  lint_hard: ^4.0.0
executables:
  full:
