name: full
version: 0.0.1
description: A sample command-line application that installs and runs mailhog
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.5.0
  dcli: 8.4.1
  dcli_core: 8.4.1
  http: ^1.2.1
  path: ^1.9.0
  settings_yaml: ^8.2.0
dev_dependencies:
  lint_hard: ^7.1.2
executables:
  full:
