name: dcli
version: 8.4.1
homepage: https://dcli.onepub.dev
documentation: https://dcli.onepub.dev
description: Dart console SDK - write console (cli) apps/scripts using dart.
repository: https://github.com/onepub-dev/dcli
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  archive: ">=3.6.1 <5.0.0"
  args: ^2.0.0
  async: ^2.5.0
  chunked_stream: ^1.4.1
  collection: ^1.15.0
  convert: ^3.0.1
  crypto: ^3.0.0
  csv: ^6.0.0
  dart_console: ^4.0.0
  dcli_common: ^8.4.1
  dcli_core: ^8.4.1
  dcli_terminal: ^8.4.1
  equatable: ^2.0.0
  ffi: ^2.0.0
  file: ^7.0.0
  glob: ^2.0.0
  ini: ^2.1.0
  logging: ^1.0.2
  meta: ">=1.11.0 <2.0.0"
  mime: ^2.0.0
  native_synchronization_temp: ^0.8.0
  path: ^1.8.0
  posix: ^6.0.1
  pub_semver: ^2.0.0
  pubspec_lock: ^3.0.1
  pubspec_manager: ^3.0.0
  scope: ^5.1.0
  settings_yaml: ^8.2.0
  stack_trace: ^1.10.0
  system_info2: ^4.0.0
  uuid: ^4.1.0
  validators2: ^5.0.0
  win32: ^5.0.0
  yaml: ^3.0.0
dev_dependencies:
  dcli_test: any
  # document_throws: ^0.1.0
  hex: ^0.2.0
  lint_hard: ^7.1.1
  mocktail: ^1.0.0
  test: ^1.0.0
  test_api: ^0.7.0
  test_core: ^0.6.0
executables:
  dcli:
platforms:
  linux:
  macos:
  windows:
