name: dcli
version: 1.20.0
homepage: https://dcli.noojee.dev
documentation: https://dcli.noojee.dev
description: Dart console SDK - write console (cli) apps/scripts using dart.
repository: https://github.com/noojee/dcli
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  archive: ^3.0.0
  args: ^2.0.0
  async: ^2.5.0
  chunked_stream: ^1.4.1
  collection: ^1.15.0
  convert: ^3.0.1
  crypto: ^3.0.0
  csv: ^5.0.1
  dart_console: ^1.0.0
  dcli_core: 1.20.0
  equatable: ^2.0.0
  ffi: ^1.1.1
  file: ^6.1.0
  glob: ^2.0.0
  ini: ^2.1.0
  logging: ^1.0.2
  meta: ^1.3.0
  mime: ^1.0.1
  path: ^1.8.0
  posix: ^3.0.0
  pub_semver: ^2.0.0
  pubspec: ^2.0.0
  scope: ^2.2.1
  settings_yaml: ^3.3.1
  stacktrace_impl: ^2.3.0
  system_info2: ^2.0.3
  uuid: ^3.0.0
  validators2: ^3.0.0
  win32: ^2.1.0
  yaml: ^3.0.0
dev_dependencies: 
  hex: ^0.2.0
  lint_hard: ^1.0.0
  mocktail: ^0.2.0
  test: ^1.0.0
executables: 
  dcli: dcli
  dcli_complete: dcli_complete
  dcli_install: dcli_install
  dshell_upgrade: dshell_upgrade
