name: dcli
version: 3.2.0-alpha.2
homepage: https://dcli.onepub.dev
documentation: https://dcli.onepub.dev
description: Dart console SDK - write console (cli) apps/scripts using dart.
repository: https://github.com/onepub-dev/dcli
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  archive: ^3.0.0
  args: ^2.0.0
  async: ^2.5.0
  chunked_stream: ^1.4.1
  collection: ^1.15.0
  convert: ^3.0.1
  crypto: ^3.0.0
  csv: ^5.0.1
  dart_console2: ^3.0.0
  dcli_core: ^3.2.0-alpha.2
  equatable: ^2.0.0
  ffi: ^2.0.0
  file: ^7.0.0
  glob: ^2.0.0
  ini: ^2.1.0
  logging: ^1.0.2
  meta: ^1.3.0
  mime: ^1.0.1
  path: ^1.8.0
  posix: ^5.0.0
  pub_semver: ^2.0.0
  pubspec_lock: ^3.0.1
  pubspec_manager: ^1.0.0-alpha.11
  scope: ^4.1.0
  settings_yaml: ^7.0.0
  stack_trace: ^1.10.0
  system_info2: ^4.0.0
  uuid: ^4.1.0
  validators2: ^5.0.0
  win32: ^4.1.4
  yaml: ^3.0.0
dev_dependencies: 
  hex: ^0.2.0
  lint_hard: ^4.0.0
  mocktail: ^1.0.0
  test: ^1.0.0
  test_api: ^0.6.0
  test_core: ^0.5.2
executables: 
  dcli: 
  dcli_complete: 
  dcli_install: 
platforms: 
  linux: 
  macos: 
  windows: 
