name: console_simple
version: 0.0.1
description: A simple command-line application created by dcli
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter:

dependencies:
  args: ^2.4.2
  dcli: 4.0.0

dev_dependencies:
  lint_hard: ^4.0.0
