name: console_simple
version: 0.0.1
description: A simple command-line application created by dcli
environment: 
  sdk: '>=2.19.0 <4.0.0'
dependencies: 
  args: ^2.3.1
  dcli: ^2.2.0
  dcli_core: ^2.2.0
  lint_hard: ^3.0.0
