name: dcli_common
version: 8.4.2
description: Common code used by multiple dcli packages.
repository: https://github.com/onepub-dev/dcli
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  meta: ">=1.11.0 <2.0.0"
  path: ^1.9.0
  scope: ^5.0.0
dev_dependencies:
  lint_hard: ^7.0.1
  test: ^1.24.0
