name: dcli_terminal
version: 8.4.2
homepage: https://dcli.onepub.dev
description: Provides Terminal/Ansi functions used by DCli the Dart Console SDK but is also intended to be used directly.
repository: https://github.com/onepub-dev/dcli
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  dart_console: ^4.0.0
dev_dependencies:
  lint_hard: ^7.1.2
  test: ^1.23.1
