name: console_simple
version: 0.0.1
description: A simple command-line application created by dcli
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  dcli: ^3.0.2
  dcli_core: ^3.0.2
dev_dependencies: 
  lint_hard: ^3.0.0
